### ISSUE TITLE
Unsupported URL https://live2.nicovideo.jp

### ISSUE THREAD

**Issue by yuusakuri** [animelover1984/youtube-dl#12]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', '-p', 'PRIVATE', 'https://live2.nicovideo.jp/watch/lv328337638', '-v']
[debug] Encodings: locale cp932, fs mbcs, out cp65001, pref cp932
[debug] youtube-dl version 2020.09.20
[debug] Python version 3.4.4 (CPython) - Windows-10-10.0.19041
[debug] exe versions: ffmpeg 4.2.2, ffprobe 4.2.2
[debug] Proxy map: {}
[generic] lv328337638: Requesting header
WARNING: Falling back on generic information extractor.
[generic] lv328337638: Downloading webpage
[generic] lv328337638: Extracting information
ERROR: Unsupported URL: https://live2.nicovideo.jp/watch/lv328337638
Traceback (most recent call last):
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\YoutubeDL.py", line 797, in extract_info
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\common.py", line 532, in extract
  File "C:\Users\dst\AppData\Roaming\Build archive\youtube-dl\ytdl-org\tmpksi3o1r1\build\youtube_dl\extractor\generic.py", line 3382, in _real_extract
youtube_dl.utils.UnsupportedError: Unsupported URL: https://live2.nicovideo.jp/watch/lv328337638

```

## Description

I ran the following code. Please forgive me for hiding my username and password.
```powershell
& 'B:\youtube-dl.exe' -u '<mailaddress>' -p '<password>' 'https://live2.nicovideo.jp/watch/lv328337638'
```
Result
```
ERROR: Unsupported URL: https://live2.nicovideo.jp/watch/lv328337638
```

**Comment by bbepis** [comment]
You are using the base youtube-dl executable to download this. The youtube-dl version you have is `2020.09.20`, however the version that the latest release of this fork prints is `2020.07.28`.

I'll close this ticket, but if you end up running into this issue with the fork's executable then please re-open this issue.
