### ISSUE TITLE
Youtube videos with zero comments results in exception

### ISSUE THREAD

**Issue by clayne** [animelover1984/youtube-dl#15]
## Checklist

- [x] I'm reporting a broken site support issue
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar bug reports including closed ones
- [x] I've read bugs section in FAQ

## Verbose log
```
ERROR: An extractor error has occurred. (caused by KeyError('contents')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "/home/clayne/git/youtube-dl-1/youtube_dl/extractor/common.py", line 533, in extract
    ie_result = self._real_extract(url)
  File "/home/clayne/git/youtube-dl-1/youtube_dl/extractor/youtube.py", line 2165, in _real_extract
    for meta_comment in item_section['contents']:
KeyError: 'contents'
Traceback (most recent call last):
  File "/home/clayne/git/youtube-dl-1/youtube_dl/extractor/common.py", line 533, in extract
    ie_result = self._real_extract(url)
  File "/home/clayne/git/youtube-dl-1/youtube_dl/extractor/youtube.py", line 2165, in _real_extract
    for meta_comment in item_section['contents']:
KeyError: 'contents'
```
## Description

If a video has zero comments the comment fetching code will blow up due to lack of a 'contents' key. My local patch looks like this:

```
diff --git a/youtube_dl/extractor/youtube.py b/youtube_dl/extractor/youtube.py
index b3251af11..bc4d4d76f 100644
--- a/youtube_dl/extractor/youtube.py
+++ b/youtube_dl/extractor/youtube.py
@@ -2162,6 +2162,10 @@ class YoutubeIE(YoutubeBaseInfoExtractor):
 
                     first_continuation = False
 
+                # handle 0 comments gracefully
+                if not 'contents' in item_section:
+                    item_section['contents'] = []
+
                 for meta_comment in item_section['contents']:
 
                     comment = meta_comment['commentThreadRenderer']['comment']['commentRenderer']
```

**Comment by bbepis** [comment]
Thank you for debugging this and providing a patch. I've applied it in a15b336

I'd mark you as the commit author but I don't know how to
