### ISSUE TITLE
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

### ISSUE THREAD

**Issue by rivke41levp656** [animelover1984/youtube-dl#17]
- [x] I'm asking a question
- [x] I've looked through the README and FAQ for similar questions
- [x] I've searched the bugtracker for similar questions including closed ones

Hello, 
I tried the latest commit `469493e` via the following process: 

Download source --> cd --> type `make` --> `pip install -r requirements.txt`
 --> run `python youtube-dl ...` 

This results in the following error:

```
Traceback (most recent call last):
  File "youtube-dl/youtube_dl/extractor/__init__.py", line 4, in <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.lazy_extractors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "youtube-dl/__main__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/__init__.py", line 43, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/extractor/extractors.py", line 45, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/extractor/anvato.py", line 12, in <module>
ModuleNotFoundError: No module named 'youtube_dl.extractor.anvato_token_generator'
```

Perhaps this happens because I haven't fully _installed_ this fork, but following the above process works without issue on release 2020.08.24m. 

I'm trying to use this fork as a python script because I want to to have the original youtube-dl installed simultaneously. I have two questions then
1) how to fix this error?
2) how to install this fork without overwriting the original ytdl?

**Comment by scribbledlines** [comment]
In the mean time, I found that using 84f19c026fc54e8793354a3bf1a1fe634e97e276 works splendidly for my needs; this is just before the Avanto code was committed.

**Comment by pukkandan** [comment]
The ` No module named 'youtube_dl.extractor.lazy_extractors'` error is expected and is properly handled. The real error here is this:

```
  File "youtube-dl/__main__.py", line 16, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/__init__.py", line 43, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/extractor/__init__.py", line 9, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/extractor/extractors.py", line 45, in <module>
  File "<frozen zipimport>", line 259, in load_module
  File "youtube-dl/youtube_dl/extractor/anvato.py", line 12, in <module>
```
