### ISSUE TITLE
Niconico playlist extractor fails to extract entries

### ISSUE THREAD

**Issue by Cak3lies** [animelover1984/youtube-dl#22]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**, specifically the current master at the time of writing (1c1ad8e).
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
C:\Users\Keiki>youtube-dl http://www.nicovideo.jp/mylist/27411728 --verbose
[debug] System config: []
[debug] User config: ['--ffmpeg-location', 'C:\\userprograms\\ffmpeg-20200831-4a11a6f-win64-static\\bin', '-f', '(bestvideo+bestaudio/best)', '-o', 'E:\\youtube-dl\\%(uploader)s [%(upload_date)s]%(title)s[%(id)s].%(ext)s', '--all-subs', '--write-sub', '--write-all-thumbnails', '--write-info-json', '--add-metadata', '--write-description', '--retries', '30']
[debug] Custom config: []
[debug] Command-line args: ['http://www.nicovideo.jp/mylist/27411728', '--verbose']
[debug] Encodings: locale cp932, fs utf-8, out utf-8, pref cp932
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.7.3 (CPython) - Windows-10-10.0.19041-SP0
[debug] exe versions: ffmpeg git-2020-08-31-4a11a6f, ffprobe git-2020-08-31-4a11a6f
[debug] Proxy map: {}
[NiconicoPlaylist] 27411728: Downloading webpage
ERROR: Unable to extract entries; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "C:\Users\Keiki\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 804, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\Keiki\AppData\Roaming\Python\Python37\site-packages\youtube_dl\YoutubeDL.py", line 825, in __extract_info
    ie_result = ie.extract(url)
  File "C:\Users\Keiki\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\common.py", line 533, in extract
    ie_result = self._real_extract(url)
  File "C:\Users\Keiki\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\niconico.py", line 759, in _real_extract
    webpage, 'entries')
  File "C:\Users\Keiki\AppData\Roaming\Python\Python37\site-packages\youtube_dl\extractor\common.py", line 1011, in _search_regex
    raise RegexNotFoundError('Unable to extract %s' % _name)
youtube_dl.utils.RegexNotFoundError: Unable to extract entries; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

The log above was generated with the test URL found in NiconicoPlaylistIE, but the same error was produced with my personal playlists.

**Comment by Cak3lies** [comment]
Tested and confirmed to be fixed by 2ca537d. Thank you.
