### ISSUE TITLE
smile_high still working in April 2021? I can't get it to work anymore

### ISSUE THREAD

**Issue by Dioxaz** [animelover1984/youtube-dl#34]
## Checklist

- [x] I'm reporting a broken site support
- [x] I've verified that I'm running youtube-dl version **2020.12.14**
- [x] I've checked that all provided URLs are alive and playable in a browser
- [x] I've checked that all URLs and arguments with special characters are properly quoted or escaped
- [x] I've searched the bugtracker for similar issues including closed ones

## Verbose log

```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['--verbose', '-u', 'PRIVATE', '-f', 'smile_high', 'https://www.nicovideo.jp/watch/sm8338129']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.12.14
[debug] Python version 3.7.9 (CPython) - Windows-7-6.1.7601-SP1
[debug] exe versions: ffmpeg N-89369-g5a93a85fd0, ffprobe N-89369-g5a93a85fd0
[debug] Proxy map: {}
[niconico] Logging in
[niconico] sm8338129: Downloading video info page
[niconico] sm8338129: Downloading HTML5 player webpage
[niconico] sm8338129: Downloading JSON metadata for h264_360p-aac_128kbps
[niconico] sm8338129: Downloading JSON metadata for h264_360p_low-aac_128kbps
[niconico] sm8338129: Downloading JSON metadata for h264_360p-aac_64kbps
[niconico] sm8338129: Downloading JSON metadata for h264_360p_low-aac_64kbps
ERROR: requested format not available
Traceback (most recent call last):
  File "F:\youtube-dl-nico\source\youtube_dl\YoutubeDL.py", line 804, in wrapper

    return func(self, *args, **kwargs)
  File "F:\youtube-dl-nico\source\youtube_dl\YoutubeDL.py", line 836, in __extract_info
    return self.process_ie_result(ie_result, download, extra_info)
  File "F:\youtube-dl-nico\source\youtube_dl\YoutubeDL.py", line 870, in process_ie_result
    return self.process_video_result(ie_result, download=download)
  File "F:\youtube-dl-nico\source\youtube_dl\YoutubeDL.py", line 1672, in process_video_result
    expected=True)
youtube_dl.utils.ExtractorError: requested format not available
```

## Description

I'm asking this question because I can't seem to be able to download older videos in smile_high format anymore. No updated status about this feature can be found on the internet, outside of a 2-month old subreddit thread (or I didn't search enough) and (now obsolete) Archiveteam and archived 4chan pages telling you to use smile_high for such videos.

I'm aware Nico shut off the backend that allowed us to download older nm encodes and smile videos somewhere after the 12th of February 2021. Direct link to such smile videos now put out 403 errors regardless if your account is Premium or not (403 errors used to be only if using a Premium account for many years). And indeed, my add-on of choice, Nicofox, became totally useless during that moment.

Now the more intriguing part comes in. I managed to download such video (the one featured in this log) in smile_high format on the 16th of February 2021 using an older exe (I'm using the most recent fork with Python 3.7 now). At that time, I was already getting 403 errors and Nicofox wouldn't work! Unfortunately I can't remember if I used my regular Premium account or my dummy non-Premium one. Also, at that time, Nicofox used to be stuck in an endless "Loading" state, now it ends up in "Failed" straight away. If I try to download it now, using the most recent fork, this is what I get in the log. And if I download it without specifying a format, I get a reencoded file from the original smile encode (same resolution but lower video and different audio bitrate).

What could have happened during that time? Did Niconico really shut of the backend for good. Is there any hope? Or it is just me missing something?

I'm asking the question here, as I consider this point important for preservation of such vestiges, and they get reencoded to lower bitrates in the "best" format.

**Comment by pukkandan** [comment]
niconico had changed a lot of stuff in their API. While a patch was made for this, we still havent managed to make smile formats work

See: https://github.com/yt-dlp/yt-dlp/issues/171#issuecomment-800958124 https://github.com/animelover1984/youtube-dl/issues/29

**Comment by animelover1984** [comment]
To my knowledge, smile_high is no longer available, but if it is, I'll add support for it.
Not sure what to make of your anecdote; could've been like an A/B test or canary deployment.

**Comment by Dioxaz** [comment]
Thank you very much for your replies. It really clears it up for me. I wasn't aware Niconico did a lot of changes to its API within that short period of time (between February and March 2021). I really wish they wouldn't discontinue the older smile format, as I'm not fan of useless retranscoding. Those older videos aren't extraordinary in terms of quality and now they do that on top.

I guess that's too bad for me because I wasn't in time for grabbing some older videos and now I'm stuck more compression artefacts than what needs to be.

If someone could reach them in Japanese about that... but in the other hand I can't see why they would bring the older smile format back (in their logic of moving on and upgrading, I guess they had to discard this older system). That's a real bummer if it's now totally inaccessible (guides on the internet should be updated in that regard). Unless someone finds an unheard way of accessing those older encodes, which is unlikely. Note that some of those older encodes could be higher in resolution than 720p. That would mean they are now lost.

Note that important, but some other third-party applications and add-ons such XBMCnico don't work anymore because of this move.
