### ISSUE TITLE
Unable to use Windows exe

### ISSUE THREAD

**Issue by josandos** [animelover1984/youtube-dl#7]
I am using the latest Windows release on a niconico live video but am running errors when attempting to use it. Here is the logs.
```
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-v', 'https://live2.nicovideo.jp/watch/lv32640075454']
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.2 (CPython) - Windows-8.1-6.3.9600
[debug] exe versions: ffmpeg 3.3.3, ffprobe 3.3.3
[debug] Proxy map: {}
Traceback (most recent call last):
  File "__main__.py", line 19, in <module>
  File "youtube_dl\__init__.pyc", line 474, in main
  File "youtube_dl\__init__.pyc", line 464, in _real_main
  File "youtube_dl\YoutubeDL.pyc", line 2044, in download
  File "youtube_dl\YoutubeDL.pyc", line 797, in extract_info
  File "youtube_dl\extractor\common.pyc", line 530, in extract
  File "youtube_dl\extractor\common.pyc", line 434, in initialize
  File "youtube_dl\extractor\niconico.pyc", line 769, in _real_initialize
  File "youtube_dl\extractor\niconico.pyc", line 772, in _login
  File "youtube_dl\extractor\common.pyc", line 1060, in _get_login_info
  File "youtube_dl\extractor\common.pyc", line 1024, in _get_netrc_login_info
AttributeError: 'NiconicoLiveIE' object has no attribute '_NETRC_MACHINE'
```

**Comment by dullahan8** [comment]
Did you uncompress the folder? It's basically complaining that it couldnt find the files it needs to run which is a typical symptom if you don't uncompress all the files.

**Comment by bbepis** [comment]
Hi,

Try out the latest release. Fixes some issues relating to starting the program: https://github.com/animelover1984/youtube-dl/releases/latest

**Comment by bbepis** [comment]
Closing issue since assumed fixed
