### ISSUE TITLE
ERROR: An extractor error has occurred. (caused by KeyError('broadcastId'))

### ISSUE THREAD

**Issue by dullahan8** [animelover1984/youtube-dl#8]
## Verbose log

```
<SOME_PATH>\youtube-dl_2020.03.24m_x64-win>youtube-dl.exe -u <MY_EMAIL> https://live2.nicovideo.jp/watch/lv327109309
[debug] System config: []
[debug] User config: []
[debug] Custom config: []
[debug] Command-line args: ['-u', 'PRIVATE', 'https://live2.nicovideo.jp/watch/lv327109309', '--verbose']
Type account password and press [Return]:
[debug] Encodings: locale cp1252, fs utf-8, out utf-8, pref cp1252
[debug] youtube-dl version 2020.03.24
[debug] Python version 3.7.2 (CPython) - Windows-10-10.0.18362
[debug] exe versions: ffmpeg 4.3.1, ffprobe 4.3.1
[debug] Proxy map: {}
[NiconicoLive] Logging in
[NiconicoLive] lv327109309: Downloading webpage
[NiconicoLive] Detected post-March 2019 HLS-based stream
ERROR: An extractor error has occurred. (caused by KeyError('broadcastId')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyc", line 531, in extract
  File "youtube_dl\extractor\niconico.pyc", line 890, in _real_extract
KeyError: 'broadcastId'
Traceback (most recent call last):
  File "youtube_dl\extractor\common.pyc", line 531, in extract
  File "youtube_dl\extractor\niconico.pyc", line 890, in _real_extract
KeyError: 'broadcastId'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "youtube_dl\YoutubeDL.pyc", line 797, in extract_info
  File "youtube_dl\extractor\common.pyc", line 544, in extract
youtube_dl.utils.ExtractorError: An extractor error has occurred. (caused by KeyError('broadcastId')); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; type  youtube-dl -U  to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
```

## Description

Testing this out, looks like the program failed to parse the key 'broadcastID' and fails to download the target video.

**Comment by bbepis** [comment]
Hi,

Please try out the latest release: https://github.com/animelover1984/youtube-dl/releases/latest

**Comment by bbepis** [comment]
Closing issue since assumed fixed
